In [1]:
import torch

In [2]:
x = torch.randn(10)

# Print out info about the tensor
print(x)

# Shape of the tensor
print(x.shape)

# Size of the tensor
print(x.size())

# Dimension of the tensor
print(x.dim())

# Data type of the tensor
x.dtype


tensor([-0.2915,  0.2534, -2.0132, -0.0738, -0.9784, -0.4995, -0.1035, -0.4183,
        -0.3620, -0.9144])
torch.Size([10])
torch.Size([10])
1


torch.float32

In [3]:
# Create two tensors and try math operations on them
tensor1 = torch.arange(0, 3, 1)
tensor2 = torch.arange(3, 6, 1)
print(f"tensor1: {tensor1}, tensor2: {tensor2}")

tensor1: tensor([0, 1, 2]), tensor2: tensor([3, 4, 5])


In [4]:
# Add two tensors
tensor1 + tensor2

tensor([3, 5, 7])

In [5]:
# Subtract two tensors
tensor1 - tensor2

tensor([-3, -3, -3])

In [6]:
# Multiply two tensors
tensor1 * tensor2

tensor([ 0,  4, 10])

In [7]:
# Divide two tensors
tensor1 / tensor2

tensor([0.0000, 0.2500, 0.4000])

In [8]:
# Modulo two tensors
tensor1 % tensor2

tensor([0, 1, 2])

In [9]:
# Use matrix multiplication
torch.matmul(tensor1, tensor2)

tensor(14)

In [18]:
# Add a dimension to the tensor
tensor11 = tensor1.unsqueeze(0)
tensor11

tensor([[0, 1, 2]])

In [21]:
# Remove a dimension
tensor11 = tensor11.squeeze(0)
tensor11

tensor([0, 1, 2])

In [29]:
# Reshape tensors
tensorToReshape = torch.arange(0, 6, 1)

tensorToReshape.reshape(3, 2)

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [26]:
tensorToReshape.reshape(2, 3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [27]:
tensorToReshape.reshape(6, 1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5]])